namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

replicaCount: 1

image:
  repository: giancarloromeo/techtrends
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 3111

livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz

resources:
  requests: 
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m
  